/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author storm
 */
public class view extends javax.swing.JFrame {
    String path;
    File fl;
    DefaultTableModel gui;

    /**
     * Creates new form view
     */
    public view() throws IOException {
        initComponents();
        path="Output/Output.txt";
        fl = new File(path);
        gui = (DefaultTableModel) jTable1.getModel();
        try (BufferedReader buff = new BufferedReader(new FileReader(fl))) {
            
            String lne;
            while ((lne = buff.readLine()) != null) {
                
                String[] infArr = lne.split(",");
                String[] ColNames = { "GIF", "Disk Size", "Amount" };
                gui.setColumnIdentifiers(ColNames);
                String dir = infArr[0];
                String objects = infArr[infArr.length - 1];
                for (int i = 1; i < infArr.length - 1; i++) {
                    Object[] rw = infArr[i].split("/");
                    Object[] ret = new Object[rw.length + 1];
                    ret[0] = dir;
                    System.arraycopy(rw, 0, ret, 1, rw.length);
                    gui.addRow(ret);
                }

                // int sumCyl = 0;
                // Object[] x1 = new Object[3];
                // x1[0] = dir;
                // x1[1] = "cylinders";
                // for (int j = 0; j < gui.getRowCount(); j++) {
                //     sumCyl += (int) gui.getValueAt(j, 2);
                // }
                // x1[2] = sumCyl;
                // gui.addRow(x1);

                Object[] x = new Object[3];
                x[0] = dir;
                x[1] = "object";
                x[2] = objects;
                gui.addRow(x);

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] {

        }));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel1.setText("PRODUCTION HISTORY");

        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(92, 92, 92).addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup().addGap(117, 117, 117).addComponent(jButton1)
                                .addGap(18, 18, 18).addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup().addGap(16, 16, 16).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1).addComponent(jButton2))
                        .addContainerGap()));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu mn = new menu();
        mn.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        fl = new File(path);
        gui.setRowCount(0);
        try (BufferedReader buff = new BufferedReader(new FileReader(fl))) {

            String lne;
            while ((lne = buff.readLine()) != null) {

                String[] infArr = lne.split(",");
                String[] ColNames = { "GIF", "Disk Size", "Amount" };
                gui.setColumnIdentifiers(ColNames);
                String dir = infArr[0];
                String objects = infArr[infArr.length - 1];
                for (int i = 1; i < infArr.length - 1; i++) {
                    Object[] rw = infArr[i].split("/");
                    Object[] ret = new Object[rw.length + 1];
                    ret[0] = dir;
                    System.arraycopy(rw, 0, ret, 1, rw.length);
                    gui.addRow(ret);
                }
                // int sumCyl = 0;
                // Object[] x1 = new Object[3];
                // x1[0] = dir;
                // x1[1] = "cylinders";
                // for (int j = 0; j < gui.getRowCount(); j++) {
                //     sumCyl += Integer.valueOf( gui.getValueAt(j, 2).toString());
                // }

                // x1[2] = sumCyl;
                // gui.addRow(x1);


                Object[] x = new Object[3];
                x[0] = dir;
                x[1] = "object";
                x[2] = objects;
                gui.addRow(x);

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }

    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
